services:
  postgres:
    image: postgres:latest
    container_name: postgres_portfolio
    environment:
      POSTGRES_USER: dashboarduser
      POSTGRES_PASSWORD: dashboardpass
      POSTGRES_DB: portfolio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
